export const mandiPrices = [
  { commodity: "Wheat", price: 2100, change: 2, unit: "quintal" },
  { commodity: "Rice", price: 3500, change: -1, unit: "quintal" },
  { commodity: "Corn", price: 1800, change: 5, unit: "quintal" },
];

export const weatherAlerts = [
  {
    type: "Moderate rainfall",
    message: "Moderate rainfall expected in northern regions tomorrow. Prepare for irrigation management.",
    severity: "moderate",
  },
];

export const quickTips = [
  {
    title: "Crop Rotation",
    description: "Rotate your crops annually to improve soil health and reduce pest infestations. Consider legume crops.",
  },
];

export const produceListings = [
  {
    id: "1",
    name: "Fresh Lettuce",
    quantity: 200,
    unit: "kg",
    price: 30,
    location: "15 km away",
    image: "https://images.pexels.com/photos/1352199/pexels-photo-1352199.jpeg?auto=compress&cs=tinysrgb&w=600",
  },
  {
    id: "2",
    name: "Golden Corn",
    quantity: 500,
    unit: "kg",
    price: 20,
    location: "22 km away",
    image: "https://images.pexels.com/photos/547263/pexels-photo-547263.jpeg?auto=compress&cs=tinysrgb&w=600",
  },
  {
    id: "3",
    name: "Ripe Tomatoes",
    quantity: 150,
    unit: "kg",
    price: 28,
    location: "10 km away",
    image: "https://images.pexels.com/photos/1327838/pexels-photo-1327838.jpeg?auto=compress&cs=tinysrgb&w=600",
  },
  {
    id: "4",
    name: "Organic Spinach",
    quantity: 100,
    unit: "kg",
    price: 40,
    location: "18 km away",
    image: "https://images.pexels.com/photos/2255935/pexels-photo-2255935.jpeg?auto=compress&cs=tinysrgb&w=600",
  },
  {
    id: "5",
    name: "Organic Wheat",
    quantity: 500,
    unit: "kg",
    price: 28,
    location: "Bengaluru, KA (15 km away)",
    image: "https://images.pexels.com/photos/326082/pexels-photo-326082.jpeg?auto=compress&cs=tinysrgb&w=600",
  },
  {
    id: "6",
    name: "Paddy Rice",
    quantity: 1000,
    unit: "kg",
    price: 35,
    location: "Hyderabad, TS (20 km away)",
    image: "https://images.pexels.com/photos/1537169/pexels-photo-1537169.jpeg?auto=compress&cs=tinysrgb&w=600",
  },
  {
    id: "7",
    name: "Fresh Tomatoes",
    quantity: 200,
    unit: "kg",
    price: 50,
    location: "Pune, MH (5 km away)",
    image: "https://images.pexels.com/photos/1327838/pexels-photo-1327838.jpeg?auto=compress&cs=tinysrgb&w=600",
  },
  {
    id: "8",
    name: "Sweet Corn",
    quantity: 300,
    unit: "kg",
    price: 20,
    location: "Chennai, TN (30 km away)",
    image: "https://images.pexels.com/photos/547263/pexels-photo-547263.jpeg?auto=compress&cs=tinysrgb&w=600",
  },
  {
    id: "9",
    name: "Potatoes (Organic)",
    quantity: 800,
    unit: "kg",
    price: 30,
    location: "Mumbai, MH (10 km away)",
    image: "https://images.pexels.com/photos/144248/potatoes-vegetables-erdfrucht-bio-144248.jpeg?auto=compress&cs=tinysrgb&w=600",
  },
  {
    id: "10",
    name: "Yellow Onions",
    quantity: 400,
    unit: "kg",
    price: 22,
    location: "Delhi, UP (25 km away)",
    image: "https://images.pexels.com/photos/533342/pexels-photo-533342.jpeg?auto=compress&cs=tinysrgb&w=600",
  },
];

export const jobPostings = [
  {
    id: "1",
    title: "Harvesting Crew Needed",
    location: "Village A, 5km away",
    workers: 5,
    wage: 500,
    duration: 7,
  },
  {
    id: "2",
    title: "Planting Assistance",
    location: "Farm B, 12km away",
    workers: 3,
    wage: 450,
    duration: 10,
  },
  {
    id: "3",
    title: "Weeding Team",
    location: "Field C, 8km away",
    workers: 4,
    wage: 400,
    duration: 5,
  },
  {
    id: "4",
    title: "Irrigation Specialist",
    location: "Orchard D, 20km away",
    workers: 1,
    wage: 600,
    duration: 15,
  },
  {
    id: "5",
    title: "Paddy Harvesting Team",
    location: "Warangal, Telangana",
    workers: 10,
    wage: 650,
    duration: "3 Weeks",
    type: "Harvesting",
    image: "https://images.pexels.com/photos/2132250/pexels-photo-2132250.jpeg?auto=compress&cs=tinysrgb&w=600",
  },
  {
    id: "6",
    title: "Organic Vegetable Planters",
    location: "Mysore, Karnataka",
    workers: 5,
    wage: 580,
    duration: "1 Month",
    type: "Planting",
    image: "https://images.pexels.com/photos/4503273/pexels-photo-4503273.jpeg?auto=compress&cs=tinysrgb&w=600",
  },
  {
    id: "7",
    title: "Irrigation System Management",
    location: "Nashik, Maharashtra",
    workers: 2,
    wage: 700,
    duration: "Ongoing",
    type: "Irrigation",
    image: "https://images.pexels.com/photos/2132227/pexels-photo-2132227.jpeg?auto=compress&cs=tinysrgb&w=600",
  },
  {
    id: "8",
    title: "Farm Equipment Operator",
    location: "Ludhiana, Punjab",
    workers: 1,
    wage: 850,
    duration: "2 Months",
    type: "Operating Machinery",
    image: "https://images.pexels.com/photos/2252602/pexels-photo-2252602.jpeg?auto=compress&cs=tinysrgb&w=600",
  },
  {
    id: "9",
    title: "Pest Control Specialist",
    location: "Guntur, Andhra Pradesh",
    workers: 2,
    wage: 720,
    duration: "Seasonal",
    type: "Pest Management",
    image: "https://images.pexels.com/photos/4503267/pexels-photo-4503267.jpeg?auto=compress&cs=tinysrgb&w=600",
  },
  {
    id: "10",
    title: "Warehouse & Logistics Assistant",
    location: "Coimbatore, Tamil Nadu",
    workers: 3,
    wage: 600,
    duration: "Permanent",
    type: "Logistics",
    image: "https://images.pexels.com/photos/162689/apple-fruit-food-healthy-162689.jpeg?auto=compress&cs=tinysrgb&w=600",
  },
];

export const marketplaceProducts = [
  {
    id: "1",
    name: "Hybrid Corn Seeds (5kg)",
    category: "seeds",
    price: 850,
    unit: "bag",
    image: "https://images.pexels.com/photos/265216/pexels-photo-265216.jpeg?auto=compress&cs=tinysrgb&w=600",
  },
  {
    id: "2",
    name: "Organic NPK Fertilizer (25kg)",
    category: "fertilizers",
    price: 1200,
    unit: "bag",
    image: "https://images.pexels.com/photos/4505135/pexels-photo-4505135.jpeg?auto=compress&cs=tinysrgb&w=600",
  },
  {
    id: "3",
    name: "Bio-Pesticide (1L)",
    category: "pesticides",
    price: 600,
    unit: "bottle",
    image: "https://images.pexels.com/photos/4750274/pexels-photo-4750274.jpeg?auto=compress&cs=tinysrgb&w=600",
  },
  {
    id: "4",
    name: "Mini Tiller Rental",
    category: "machinery",
    price: 450,
    unit: "day",
    isRental: true,
    image: "https://images.pexels.com/photos/2132250/pexels-photo-2132250.jpeg?auto=compress&cs=tinysrgb&w=600",
  },
  {
    id: "5",
    name: "High-Yield Wheat Seeds",
    category: "seeds",
    price: 1500,
    unit: "bag",
    image: "https://images.pexels.com/photos/326082/pexels-photo-326082.jpeg?auto=compress&cs=tinysrgb&w=600",
  },
  {
    id: "6",
    name: "Urea Fertilizer (50kg)",
    category: "fertilizers",
    price: 1800,
    unit: "bag",
    image: "https://images.pexels.com/photos/4505135/pexels-photo-4505135.jpeg?auto=compress&cs=tinysrgb&w=600",
  },
  {
    id: "7",
    name: "Tractor (50HP) Rental",
    category: "machinery",
    price: 2500,
    unit: "day",
    isRental: true,
    image: "https://images.pexels.com/photos/2252602/pexels-photo-2252602.jpeg?auto=compress&cs=tinysrgb&w=600",
  },
  {
    id: "8",
    name: "Insecticide Granules (5kg)",
    category: "pesticides",
    price: 750,
    unit: "box",
    image: "https://images.pexels.com/photos/4750274/pexels-photo-4750274.jpeg?auto=compress&cs=tinysrgb&w=600",
  },
  {
    id: "9",
    name: "Organic Wheat Seeds (25kg)",
    category: "seeds",
    price: 1200,
    unit: "bag",
    image: "https://images.pexels.com/photos/265216/pexels-photo-265216.jpeg?auto=compress&cs=tinysrgb&w=600",
  },
  {
    id: "10",
    name: "NPK Fertilizer 18:46:0 (50kg)",
    category: "fertilizers",
    price: 850,
    unit: "bag",
    image: "https://images.pexels.com/photos/4505135/pexels-photo-4505135.jpeg?auto=compress&cs=tinysrgb&w=600",
  },
  {
    id: "11",
    name: "High-Yield Corn Seeds (10kg)",
    category: "seeds",
    price: 980,
    unit: "bag",
    image: "https://images.pexels.com/photos/547263/pexels-photo-547263.jpeg?auto=compress&cs=tinysrgb&w=600",
  },
  {
    id: "12",
    name: "Organic Compost (20kg Bag)",
    category: "organic",
    price: 300,
    unit: "bag",
    image: "https://images.pexels.com/photos/4505135/pexels-photo-4505135.jpeg?auto=compress&cs=tinysrgb&w=600",
  },
  {
    id: "13",
    name: "Sun-dried Tomato Seeds",
    category: "seeds",
    price: 150,
    unit: "packet",
    image: "https://images.pexels.com/photos/1327838/pexels-photo-1327838.jpeg?auto=compress&cs=tinysrgb&w=600",
  },
  {
    id: "14",
    name: "Foliar Spray NutriBoost (5 Liters)",
    category: "fertilizers",
    price: 1100,
    unit: "bottle",
    image: "https://images.pexels.com/photos/4750274/pexels-photo-4750274.jpeg?auto=compress&cs=tinysrgb&w=600",
  },
];

export const forumPosts = [
  {
    id: "1",
    author: "Sunil Sharma",
    avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Sunil",
    time: "2 hours ago",
    content: "My tomato plants are showing yellowing leaves. Is it a nutrient deficiency or something else? Any advice from experienced farmers?",
    image: "https://images.pexels.com/photos/1327838/pexels-photo-1327838.jpeg?auto=compress&cs=tinysrgb&w=600",
    upvotes: 45,
    comments: 12,
  },
  {
    id: "2",
    author: "Priya Singh",
    avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Priya",
    time: "1 day ago",
    content: "Just harvested a bumper crop of organic potatoes! So proud of the yield this season. Sharing a picture!",
    image: "https://images.pexels.com/photos/144248/potatoes-vegetables-erdfrucht-bio-144248.jpeg?auto=compress&cs=tinysrgb&w=600",
    upvotes: 120,
    comments: 38,
  },
  {
    id: "3",
    author: "Rajesh Kumar",
    avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Rajesh",
    time: "3 days ago",
    content: "Looking for tips on natural pest control for corn. Tried neem oil, but the armyworms are persistent. Any organic solutions?",
    image: "https://images.pexels.com/photos/547263/pexels-photo-547263.jpeg?auto=compress&cs=tinysrgb&w=600",
    upvotes: 78,
    comments: 25,
  },
  {
    id: "4",
    author: "Anjali Desai",
    avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Anjali",
    time: "5 days ago",
    content: "Excited to share our new initiative on sustainable irrigation techniques. We're seeing a 30% reduction in water usage! Ask me anything about it.",
    image: "https://images.pexels.com/photos/2132227/pexels-photo-2132227.jpeg?auto=compress&cs=tinysrgb&w=600",
    upvotes: 90,
    comments: 19,
  },
  {
    id: "5",
    author: "Ramesh Singh",
    avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Ramesh",
    time: "2 hours ago",
    content: "My tomato plants are showing yellowing leaves. Could this be a nutrient deficiency or pest issue? Any advice on how to treat it naturally?",
    image: "https://images.pexels.com/photos/1327838/pexels-photo-1327838.jpeg?auto=compress&cs=tinysrgb&w=600",
    upvotes: 25,
    comments: 7,
  },
  {
    id: "6",
    author: "Priya Sharma",
    avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Priya",
    time: "5 hours ago",
    content: "Looking for best practices for organic pest control in corn fields. What are your most effective homemade remedies and biological solutions?",
    image: "https://images.pexels.com/photos/547263/pexels-photo-547263.jpeg?auto=compress&cs=tinysrgb&w=600",
    upvotes: 18,
    comments: 4,
  },
  {
    id: "7",
    author: "Anil Kumar",
    avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Anil",
    time: "1 day ago",
    content: "Has anyone successfully used drip irrigation for potato farming in arid regions? Share your setup and yield results!",
    image: "https://images.pexels.com/photos/2132227/pexels-photo-2132227.jpeg?auto=compress&cs=tinysrgb&w=600",
    upvotes: 32,
    comments: 11,
  },
  {
    id: "8",
    author: "Sneha Reddy",
    avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Sneha",
    time: "2 days ago",
    content: "Tips for maximizing soil health in vegetable gardens. I want to improve fertility naturally. Which compost methods work best?",
    image: "https://images.pexels.com/photos/4505135/pexels-photo-4505135.jpeg?auto=compress&cs=tinysrgb&w=600",
    upvotes: 40,
    comments: 15,
  },
  {
    id: "9",
    author: "Vijay Patel",
    avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Vijay",
    time: "3 days ago",
    content: "What are the benefits of crop rotation for small farms? And what rotation schedule do you recommend for fruits and vegetables?",
    upvotes: 15,
    comments: 3,
  },
];

export const governmentSchemes = [
  {
    id: "1",
    name: "PM-KISAN",
    description: "Direct income support of ₹6000 per year to farmer families",
    deadline: "March 31, 2025",
    eligibility: "All landholding farmers",
  },
  {
    id: "2",
    name: "Soil Health Card Scheme",
    description: "Free soil testing and health cards for farmers",
    deadline: "Ongoing",
    eligibility: "All farmers",
  },
  {
    id: "3",
    name: "Pradhan Mantri Fasal Bima Yojana",
    description: "Crop insurance scheme for farmers",
    deadline: "Before sowing season",
    eligibility: "All farmers growing notified crops",
  },
  {
    id: "4",
    name: "Kisan Credit Card",
    description: "Easy access to credit for farmers",
    deadline: "Ongoing",
    eligibility: "All farmers with land records",
  },
];
